node_modules/.yarn-integrity
packages/app/src/Publishers.tsx
packages/app/src/index.tsx

This way, when you go to `/` you see a list of publishers, which links you to each respective publisher page

adds publisher page and makes index not need address

---

packages/app/src/App.tsx
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/commons/UploadFile.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/components/PermissionSection.tsx
packages/app/src/components/views/publication/components/PostSection.tsx
packages/app/src/models/publication.ts
packages/app/src/services/poster/hooks/usePoster.ts
packages/app/src/services/poster/type.ts
packages/app/src/services/publications/queries.ts
packages/app/src/utils/permission.ts

closed #9 
This PR contains the update and delete action, just if the users have the proper permissions.
Test:
https://rinkeby.etherscan.io/tx/0x3113f2e833e0169fc3a314ba7db887fb1ac62714fb18d1a70b3052e63d04183d
https://rinkeby.etherscan.io/tx/0x52edc2df7ee77fd9ec7a00f6e71675ff217362bf01f878f1a518ec85d11eee91
https://rinkeby.etherscan.io/tx/0x1dba22192f7ecb6d29656efab8e0620b3bd6a2ec167020420323285e2e80e823

Article actions flow

---

.github/workflows/ci.yaml
.github/workflows/dev-cd.yaml
.github/workflows/prod-release-deploy.yaml
packages/app/src/components/commons/PermissionItem.tsx
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/home/LandingView.tsx
packages/subgraph/package.json

following https://github.com/gnosis/tabula/pull/37

Update publication flow

---

packages/app/src/App.tsx
packages/app/src/components/commons/PermissionItem.tsx
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/home/LandingView.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublicationPostView.tsx
packages/app/src/components/views/publication/components/PostSection.tsx
packages/app/src/components/views/publication/components/PublicationTabs.tsx
packages/app/src/models/publication.ts
packages/app/src/utils/permission.ts

Article UI redirection

---

packages/app/src/App.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/publication/PublicationPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/components/views/wallet/WalletView.tsx
packages/app/src/services/publications/contexts/publication.context.tsx
packages/app/src/services/publications/contexts/publication.types.ts
packages/app/src/theme/index.ts

closed #13 
Test url: `/#/publication/post/P-0x50c7493bbaa5380152e37f0c7f7295399f41d5eae4657083a9abf2f0b4503407-26`
UI:

Make it possible for a user to view a list of articles posted

---

packages/app/src/App.tsx
packages/app/src/components/commons/PinningAlert.tsx
packages/app/src/components/commons/UserOptions.tsx
packages/app/src/components/layout/Header.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/pinning/SetupIpfsView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/components/views/publication/components/PublicationTabs.tsx
packages/app/src/components/views/wallet/WalletView.tsx
packages/app/src/hooks/useEventListener.ts
packages/app/src/hooks/useLocalStorage.ts
packages/app/src/models/pinning.ts

Create setup IPFS View

---

packages/app/.env.example
packages/app/src/App.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/wallet/SelectNetwork.tsx
packages/app/src/components/views/wallet/WalletView.tsx
packages/app/src/connectors/index.ts
packages/app/src/constants/chain.ts
packages/app/src/hooks/useFiles.ts
packages/app/src/models/publication.ts
packages/app/src/services/graphql.ts
packages/app/src/services/publications/hooks/usePublication.ts
packages/subgraph/.env.sample
packages/subgraph/package.json
packages/subgraph/src/publication.mapping.ts

~~I think the functionality is there, however the modal/prompt for changing chains still requires some UI work.~~
~~Also, https://github.com/gnosis/tabula/issues/56#issuecomment-1116933628 is missing.~~
Closes #56 
Closes #62 
+ various other stuff needed for supporting multiple chains.

Support multiple chains

---

packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/theme/index.ts

PostItem Design updates and thumbnail integration:
Article thumbnail:

Implements Thumbnail Imagery

---

packages/app/src/components/commons/PermissionItem.tsx
packages/app/src/components/commons/PinningAlert.tsx
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/commons/PublicationItem.tsx
packages/app/src/components/commons/UploadFile.tsx
packages/app/src/components/commons/UserOptions.tsx
packages/app/src/components/commons/WalletBadge.tsx
packages/app/src/components/commons/WalletButton.tsx
packages/app/src/components/layout/Header.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/pinning/SetupIpfsView.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PermissionView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/theme/index.ts

UI updates

---

packages/app/src/components/views/publication/PublicationPostView.tsx
packages/app/src/components/views/publication/components/PublicationTabs.tsx
packages/app/src/components/views/publication/components/SettingSection.tsx
packages/app/src/services/poster/hooks/usePoster.ts
packages/app/src/services/poster/type.ts

@juliopavila I've added a button here. I haven't added the deletePublication logic for #87 yet.

Add Delete Publication Button (fixes #87)

---

packages/app/src/components/commons/PostItem.tsx

closed #82 
Url to test: http://localhost:3000/#/publication/rinkeby:P-0x1d3c7e7dbee9b7e707d9412284b79b283b33622c48f0bda899ff8c9814ed65aa-32

Change the continue reading button name

---

packages/app/src/components/commons/WalletBadge.tsx

closed #79 
The address avatar should be the same everywhere

Solved mismatched blockies bug

---

packages/app/src/components/commons/UserOptions.tsx

Implement easy way to get back to publish view

---

packages/app/src/components/commons/Dropdown.tsx
packages/app/src/components/views/pinning/SetupIpfsView.tsx
packages/app/src/constants/pinning.ts
packages/app/src/hooks/useFiles.ts
packages/app/src/models/dropdown.ts
packages/app/src/models/pinning.ts

closed #72 
**New UI for IPFS**
**Valid IPFS Service**
https://user-images.githubusercontent.com/19823989/173875244-3715332c-6186-41d4-af8a-acf564e6eea7.mov
**Invalid IPFS Service**
https://user-images.githubusercontent.com/19823989/173875083-5b4a0d37-1449-4ef8-9032-6050a68a27a3.mov

Refactor IPFS screen and valide IPFS node input

---

packages/app/src/components/commons/WalletBadge.tsx
packages/app/src/components/views/publication/ArticleView.tsx

closed #83 
Test url:
```/#/publication/rinkeby:P-0xb36b158430fa42fd2ea776534c10aa92906b87a3ca2136fbd7fcd15d4f08177e-181/article/A-0x120b426e8c378d3bb7783e2ea89c4aea29ed85c0817a86b6938a8567143cdb59-132```
UI:

Add author to article

---

packages/app/src/components/commons/WalletBadge.tsx
packages/app/src/components/views/publication/ArticleView.tsx

Revert "Add author to article"

---

packages/app/src/components/commons/WalletBadge.tsx
packages/app/src/components/views/publication/ArticleView.tsx

Revert "Revert "Add author to article""

---

packages/app/package.json
packages/app/src/components/commons/CreatableSelect.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/components/views/publication/components/SettingSection.tsx
packages/app/src/models/dropdown.ts
packages/app/yarn.lock

closed #84 
closed #97
Tasks completed
**Create Publication Screen UI**
**Settings Screen UI**
**Preview Article Screen UI**

Add multiples authors to post

---

packages/app/src/hooks/useFiles.ts

closed #68 
Record
https://user-images.githubusercontent.com/19823989/174636749-2cbb256b-a4cf-4173-a294-83168fd1821a.mov

Don't show an error when uploading a file to IPFS that is already pinned

---

packages/app/src/App.tsx
packages/app/src/components/commons/UserOptions.tsx
packages/app/src/components/views/wallet/WalletView.tsx
packages/app/src/connectors/WalletProvider.tsx

closed #91 
Record testing
https://user-images.githubusercontent.com/19823989/174672851-c17663ff-891f-4afd-9bd5-9339dac0adcb.mov

Persistent wallet connection

---

packages/subgraph/schema.graphql
packages/subgraph/src/article.mapping.ts
packages/subgraph/src/publication.mapping.ts
packages/subgraph/src/utils.ts
packages/subgraph/tests/article.test.ts

This PR resolves the issue of null elements in articles and permissions.
Rinkeby: https://thegraph.com/hosted-service/subgraph/auryn-macmillan/tabula-rinkeby
Mainnet: https://thegraph.com/hosted-service/subgraph/auryn-macmillan/tabula-mainnet
Gnosis Chain: https://thegraph.com/hosted-service/subgraph/auryn-macmillan/tabula-gnosis-chain
closes #121

Issue-121#_no_null_publication_field

---

packages/subgraph/src/article.mapping.ts
packages/subgraph/src/mapping.ts

Issue#123_handle_falsy_update

---

packages/app/src/App.tsx
packages/app/src/components/layout/Page.tsx
packages/app/src/components/layout/PublicationPage.tsx
packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PermissionView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/components/views/publication/components/SettingSection.tsx
packages/app/src/hooks/useNotification.tsx
packages/app/src/services/poster/context/index.ts
packages/app/src/services/poster/context/poster.context.tsx
packages/app/src/services/poster/context/poster.types.ts
packages/app/src/services/poster/hooks/usePoster.ts
packages/app/src/services/publications/hooks/useArticles.ts
packages/app/src/services/publications/hooks/usePublication.ts
packages/app/src/services/publications/hooks/usePublications.ts
packages/app/src/services/publications/queries.ts

closed #60 
I made a refactor of how to handle the indexing flow to every contract interaction and moved logic code from the UI Component to custom hooks.

Refactor how to show the toast

---

packages/app/.env.example
packages/app/src/components/commons/UploadFile.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/components/PostSection.tsx
packages/app/src/hooks/useFiles.ts
packages/app/src/hooks/useNotification.tsx
packages/app/src/services/poster/hooks/usePoster.ts
packages/app/src/services/publications/hooks/useArticles.ts
packages/app/src/services/publications/hooks/usePublication.ts
packages/app/src/services/publications/hooks/usePublications.ts

closed #94 
Please merge first the following PRs: #115 #116 
Completed tasks:
- Fix some bugs related to the PR #115 #116 
- Refactor the way that we have been sending the image to the contract
- Bring the user the possibility to remove an image from the post
- Solved some UX bugs

Delete preview image from post

---

packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx

Remove state when leaving the new post/edit post view

---

packages/app/src/App.tsx
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/layout/Page.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/layout/PublicationPage.tsx
packages/app/src/components/views/pinning/SetupIpfsView.tsx
packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/components/views/publication/components/PermissionSection.tsx
packages/app/src/components/views/publication/components/PostSection.tsx
packages/app/src/connectors/WalletProvider.tsx
packages/app/src/constants/chain.ts
packages/app/src/services/poster/context/poster.context.tsx
packages/app/src/services/poster/context/poster.types.ts
packages/app/src/services/poster/hooks/usePoster.ts
packages/app/src/utils/validation.ts

closed #100 
Record:
https://user-images.githubusercontent.com/19823989/175619496-a8613adc-e677-4766-bcec-79d99e95aea4.mov

[Solved] - Do not trigger transactions on the wrong network

---

packages/subgraph/src/article.mapping.ts
packages/subgraph/src/publication.mapping.ts
packages/subgraph/tests/publication.test.ts
packages/subgraph/tests/util.ts

Bug in publication´s permission array

---

packages/app/src/App.tsx
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/components/views/publication/CreatePostView.tsx
packages/app/src/components/views/publication/PermissionView.tsx
packages/app/src/components/views/publication/PreviewPostView.tsx
packages/app/src/components/views/publication/PublicationPostView.tsx
packages/app/src/components/views/publication/PublishView.tsx
packages/app/src/components/views/publication/components/SettingSection.tsx
packages/app/src/components/views/wallet/SelectNetwork.tsx
packages/app/src/components/views/wallet/WalletView.tsx
packages/app/src/models/publication.ts
packages/app/src/services/graphql.ts
packages/subgraph/src/publication.mapping.ts
packages/subgraph/src/utils.ts

- the subgraph converts old xdai name to gnosis_chain (The Graph still uses xdai)
Fix #133 
Fix #134 
Also, fixes some notification issues

Update the publication ID to include `gnosis-chain` instead of `xdai`

---

packages/app/public/index.html
packages/app/src/components/layout/PublicationPage.tsx
packages/app/src/components/views/publication/ArticleView.tsx

Manboy eth/issue49

---

packages/app/src/components/commons/UploadFile.tsx

https://discord.com/channels/@me/953666061591531530/999369540859330650

allows user to change thumbnail without deleting it first.

---

packages/app/src/components/commons/PostItem.tsx
packages/app/src/theme/index.ts

- Revises the h1 styles on mobile for better legibility
- Allows tags to wrap and flow in the post previews

Minor style improvements

---

packages/app/src/components/commons/Markdown.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/theme/index.ts

This resolves the remaining markdown formatting issues (with the exception of footnote links) and closes #136

Resolves formatting issues mentioned in issue #136

---

packages/app/src/components/views/publication/CreatePostView.tsx

After I merged my update to showcase write/preview tabs, it didn't account for "editing" posts, so it doesn't grab the existing data.
Fixes #163

Fixes Edit Post bug

---

.github/workflows/dev-cd.yaml
.github/workflows/prod-release-deploy.yaml
packages/app/.env.example
packages/app/src/components/commons/PostItem.tsx
packages/app/src/components/commons/PublicationAvatar.tsx
packages/app/src/components/commons/PublicationItem.tsx
packages/app/src/components/commons/UploadFile.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/components/views/publication/PublicationPostView.tsx
packages/app/src/services/ipfs/ipfs.ts

Extracts the hardcoded IPFS gateway into an environment variable.
Fixes #168
The IPFS gateway that we have been relying on is deprecated: https://blog.infura.io/post/ipfs-public-api-and-gateway-deprecation

Extracts the hardcoded IPFS gateway into an environment variable

---

packages/app/src/App.tsx
packages/app/src/components/layout/PublicationHeader.tsx
packages/app/src/components/views/publication/CreateArticleView.tsx
packages/app/src/components/views/publication/CreateArticleView2.tsx
packages/app/src/components/views/publication/PermissionView.tsx
packages/app/src/components/views/publication/PublicationView.tsx
packages/app/src/components/views/publication/PublicationsView.tsx
packages/app/src/components/views/publication/components/ArticleItem.tsx
packages/app/src/components/views/publication/components/ArticleSection.tsx
packages/app/src/components/views/publication/components/ArticleTabs.tsx
packages/app/src/components/views/publication/components/PublicationTabs.tsx

General Refactoring

---

.github/workflows/dev-cd.yaml
.github/workflows/prod-release-deploy.yaml
.gitignore
packages/app/.env.example
packages/app/package.json
packages/app/src/components/commons/IPFSNodeModal.tsx
packages/app/src/components/commons/PublicationAvatar.tsx
packages/app/src/components/commons/UploadFile.tsx
packages/app/src/components/commons/UserOptions.tsx
packages/app/src/components/views/publication/CreateArticleView2.tsx
packages/app/src/components/views/publication/PublicationsView.tsx
packages/app/src/components/views/publication/components/PublicationTabs.tsx
packages/app/src/components/views/publication/components/SettingSection.tsx
packages/app/src/hooks/useIpfs.ts
packages/app/src/services/ipfs.ts
packages/app/src/services/publications/contexts/publication.context.tsx
packages/app/src/services/publications/hooks/useArticle.ts
packages/app/src/services/publications/hooks/usePublication.ts
packages/app/yarn.lock

closes #27 
FYI: https://github.com/gnosis/tabula/issues/27#issuecomment-1400821921
UI

Stop relying exclusively on Infura for IPFS

---

packages/app/src/components/commons/WalletBadge.tsx
packages/app/src/components/views/publication/ArticleView.tsx
packages/app/src/hooks/useIpfs.ts

closes #158 
This PR contains the integration for copying the user's address.
Test
https://user-images.githubusercontent.com/19823989/214863724-d2c46c26-c7c5-45ee-a000-e4986cee6907.mov

Author tags copyable

---

packages/app/package.json
packages/app/src/components/commons/Markdown.tsx
packages/app/src/components/commons/WalletBadge.tsx
packages/app/src/components/layout/Page.tsx
packages/app/src/components/layout/PublicationPage.tsx
packages/app/src/hooks/useIpfs.ts
packages/app/src/react-app-env.d.ts
packages/app/yarn.lock
packages/subgraph/src/utils.ts

Add ENS name

---

packages/app/package.json
packages/app/yarn.lock
packages/subgraph/schema.graphql
packages/subgraph/src/publication.mapping.ts
packages/subgraph/src/utils.ts
packages/subgraph/tests/publication.test.ts

Related to #179 
@manboy-eth made this code
This is the reason for this improvement https://github.com/gnosis/tabula/pull/179#discussion_r1038373935

[Subgraph]: Publication hash

---

.github/workflows/ci.yaml
.github/workflows/dev-cd.yaml
.github/workflows/prod-release-deploy.yaml
packages/app/.env.example
packages/app/src/connectors/index.ts
packages/app/src/constants/chain.ts
packages/app/src/services/graphql.ts
packages/subgraph/network_configs/sepolia.json
packages/subgraph/package.json

> Goerli will be deprecated at the end of the year; furthermore, the network's high cost makes it difficult to test the app.
closes #224

Add sepolia network
